site_name: Team 5152 Robot Documentation
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: grey
nav:
  - Home: index.md
  - Game:
  - Library:
      - Commands:
      - Subsystems:
  - API Documentation: ./javadoc
repo_url: https://github.com/5152alotobots/5152_Template
repo_name: 5152Alotobots/5152_Template
