site_name: Team 5152 Robot Documentation
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: grey
nav:
  - Home: index.md
  - Game: []
  - Library:
      - Commands: []
      - Subsystems:
          - Swerve: library/subsystems/swerve.md
  - API Documentation: javadoc/index.html # Point directly to index.html

repo_url: https://github.com/5152alotobots/5152_Template
repo_name: 5152Alotobots/5152_Template

# Optional but recommended additions:
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

plugins:
  - search