name: Documentation
on:
  push:
    branches: ['master']

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Download Dependencies
        run: ./gradlew dependencies

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install mkdocs mkdocs-material

      - name: Generate and Copy Javadoc First
        run: |
          ./gradlew build
          ./gradlew javadoc
          mkdir -p docs/mkdocs/docs/javadoc
          cp -r build/docs/javadoc/* docs/mkdocs/docs/javadoc/

      - name: Build MkDocs
        run: |
          cd docs/mkdocs
          mkdocs build
          mkdir -p ../../site
          cp -r site/* ../../site/
          echo "Site directory after MkDocs build:"
          ls -la ../../site/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site