name: Documentation
on:
  push:
    branches: ['*']

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup Java and Python
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Setup Gradle (like in your build workflow)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      # Let Gradle handle dependencies
      - name: Download Dependencies
        run: ./gradlew dependencies

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install documentation tools
      - run: pip install mkdocs mkdocs-material

      # Generate documentation
      - name: Generate Javadoc
        run: |
          mkdir -p docs/javadoc
          ./gradlew javadoc
          cp -r build/docs/javadoc/* docs/javadoc/

      - run: mkdocs build -f docs/mkdocs/mkdocs.yml -d ../../site

      # Publish to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site