name: Documentation
on:
  push:
    branches: ['*']

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install mkdocs mkdocs-material
      - run: |
          mkdir -p docs/javadoc
          ./gradlew delombok
          javadoc -d docs/javadoc -sourcepath build/generated/sources/delombok/java/main -subpackages frc.alotobots
      - run: mkdocs build -f docs/mkdocs/mkdocs.yml -d ../../site
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
