name: Documentation
on:
  push:
    branches: ['*']

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Download Dependencies
        run: ./gradlew dependencies

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install mkdocs mkdocs-material

      - name: Build MkDocs
        run: mkdocs build -f docs/mkdocs/mkdocs.yml -d site

      - name: Generate and Copy Javadoc
        run: |
          echo "Generating Javadocs..."
          ./gradlew javadoc
          echo "Creating javadoc directory..."
          mkdir -p site/javadoc
          echo "Copying Javadocs..."
          cp -r build/docs/javadoc/* site/javadoc/
          echo "Verifying site contents..."
          ls -la site/
          ls -la site/javadoc/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site